---
exclude: ^bin/
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v1.2.3
  hooks:
  - id: check-added-large-files
  - id: check-byte-order-marker
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-xml
  - id: check-yaml
  - id: detect-aws-credentials
    args:
    - --allow-missing-credentials
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: forbid-new-submodules
  - id: mixed-line-ending
  - id: pretty-format-json
    args: [
     --autofix,
     --no-sort-keys,
     --indent, '4'
    ]
  - id: requirements-txt-fixer
  - id: sort-simple-yaml
  - id: trailing-whitespace
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.19.0
  hooks:
  - id: markdownlint
