---
plugins:
  - jekyll-include-cache
remote_theme: mmistakes/minimal-mistakes@4.15.1

search: true
author:
  name: ipwnponies
  bio:
    I love food, programming, and useless trivia. Often I'll lose myself down a rabbit hole. Or an experiment that ended
    in disappointment. Let's document this so I can pretend I got smarter everyday.
  links:
    - label: "Github"
      icon: fab fa-fw fa-github
      url: https://github.com/ipwnponies

include:
  - _pages

defaults:
  # default default
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true
      toc: true
      toc_sticky: true
      toc_label: On This Page
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      read_time: true

# Collections
collections:
  recipes:
    output: true
    permalink: /:collection/:path/

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
